# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: app
          image: mingduan64/product-catalog-service:1.0.0
          ports:
            - containerPort: 8080
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: product-catalog-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer