#spring.application.name=config-server
#server.port=8088
#spring.profiles.active=native
#
## URI of GIT repo containing properties
#spring.cloud.config.server.git.uri=https://github.com/mingdoan/microservice-openAPI-demo.git
#
## path to properties from root of repo
#spring.cloud.config.server.git.searchPaths: configuration
#
#logging.level.org.springframework.web=INFO

server:
  port: 8088
spring:
  profiles:
    active: native